name: dart_connect_metro
description: This SDK provides convenient access to information, including
  real-time updates and schedules, allowing developers to enhance the
  functionality of their DC Metro-related apps.
version: 0.1.2
repository: https://github.com/babincc/flutter_workshop/tree/master/packages/dart_connect_metro
issue_tracker: https://github.com/babincc/flutter_workshop/issues?q=is%3Aissue+is%3Aopen+label%3A%22package%3A+dart_connect_metro%22

topics:
  - dc-metro
  - dc-transit

funding:
  - https://www.buymeacoffee.com/babincc
  - https://paypal.me/cssbabin
  - https://venmo.com/u/babincc

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  collection: ^1.17.0
  http: ^1.1.0

dev_dependencies:
  test: ^1.24.4
  flutter_lints: ^2.0.0
