/// Flutter icons HueIconV1
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
library;

import 'package:flutter/widgets.dart';

/// All of the old Philips Hue icons.
@Deprecated('Use HueIcon instead')
class HueIconV1 {
  HueIconV1._();

  static const _kFontFam = 'HueIconV1';
  static const String _kFontPkg = 'flutter_hue';

  static const IconData bollard =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData ceilingRound =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData ceilingSquare =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData deskLamp =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData doubleSpot =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData floorLantern =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData floorShade =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData floorSpot =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData pendantLong =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData pendantRound =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData recessedCeiling =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData recessedFloor =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData singleSpot =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData tableShade =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData tableWash =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData wallLantern =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData wallShade =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData wallSpot =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData candle =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData flood =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData foh =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData generalGroup =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData group =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData classic =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData filament =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData spot =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData sultan =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData bridgesV1 =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData bridgesV2 =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData dimmerSwitch =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData friendsOfHue =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData motionSensor =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData outdoorMotionSensor =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData plug =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData tap =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData disclosure =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData exploreHueLabs =
      IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData exploreWhatsNew =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData bloom =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData hueGo =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData huePlay =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData iris =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData strip =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData directionDiffusedLight =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData directionDownwards =
      IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData directionLeftwards =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData directionOmni =
      IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData directionRightwards =
      IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData directionUpwards =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData christmasTree =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData fire =
      IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData heart =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData music =
      IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData otherReading =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData security =
      IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData star =
      IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData watchingMovie =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData concentrate =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData dimmerDimDown =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData dimmerDimUp =
      IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData energize =
      IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData nightlight =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData presetsReading =
      IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData relax =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData attic =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData balcony =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData bathroom =
      IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData bedroom =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData carport =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData closet =
      IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData computer =
      IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData dining =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData driveway =
      IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData frontDoor =
      IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData garage =
      IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData guestroom =
      IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData gym =
      IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData hallway =
      IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData kidsBedroom =
      IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData kitchen =
      IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData laundryRoom =
      IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData living =
      IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData lounge =
      IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData manCave =
      IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData nursery =
      IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData office =
      IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData other =
      IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData outdoor =
      IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData outdoorSocialTime =
      IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData pool =
      IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData porch =
      IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData recreation =
      IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData socialTime =
      IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData staircase =
      IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData storage =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData studio =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData terrace =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData toilet =
      IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData comingHome =
      IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData daytime =
      IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData goToSleep =
      IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData homeAway =
      IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData leavingHome =
      IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData location =
      IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData nighttime =
      IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData otherApps =
      IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData personal =
      IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData sunrise =
      IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData sunset =
      IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData timers =
      IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData wakeUp =
      IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData about =
      IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData appleWatch =
      IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData devices =
      IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData feedback =
      IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData homekitSiri =
      IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData httpsConnected =
      IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData login =
      IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData messaging =
      IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData softwareUpdate =
      IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData widgets =
      IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData widgetsWatch =
      IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData automation =
      IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData explore =
      IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData home =
      IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData homeNoCon =
      IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData routines =
      IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData settings =
      IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData settingsLts =
      IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData attention =
      IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData blink =
      IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData colorloop =
      IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData colorScenes =
      IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData confirmed =
      IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData destroy =
      IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData doNothing =
      IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData dynamicScenes =
      IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData edit =
      IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData error =
      IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData export =
      IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData lastState =
      IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData lightList =
      IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData minus =
      IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData motionSensitivity =
      IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData noMotion =
      IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData photoScene =
      IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData plus =
      IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData scenes =
      IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData switchOff =
      IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData switchOn =
      IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData firstFloor =
      IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData groundFloor =
      IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData secondFloor =
      IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const List<IconData> allIcons = [
    bollard,
    ceilingRound,
    ceilingSquare,
    deskLamp,
    doubleSpot,
    floorLantern,
    floorShade,
    floorSpot,
    pendantLong,
    pendantRound,
    recessedCeiling,
    recessedFloor,
    singleSpot,
    tableShade,
    tableWash,
    wallLantern,
    wallShade,
    wallSpot,
    candle,
    flood,
    foh,
    generalGroup,
    group,
    classic,
    filament,
    spot,
    sultan,
    bridgesV1,
    bridgesV2,
    dimmerSwitch,
    friendsOfHue,
    motionSensor,
    outdoorMotionSensor,
    plug,
    tap,
    disclosure,
    exploreHueLabs,
    exploreWhatsNew,
    bloom,
    hueGo,
    huePlay,
    iris,
    strip,
    directionDiffusedLight,
    directionDownwards,
    directionLeftwards,
    directionOmni,
    directionRightwards,
    directionUpwards,
    christmasTree,
    fire,
    heart,
    music,
    otherReading,
    security,
    star,
    watchingMovie,
    concentrate,
    dimmerDimDown,
    dimmerDimUp,
    energize,
    nightlight,
    presetsReading,
    relax,
    attic,
    balcony,
    bathroom,
    bedroom,
    carport,
    closet,
    computer,
    dining,
    driveway,
    frontDoor,
    garage,
    guestroom,
    gym,
    hallway,
    kidsBedroom,
    kitchen,
    laundryRoom,
    living,
    lounge,
    manCave,
    nursery,
    office,
    other,
    outdoor,
    outdoorSocialTime,
    pool,
    porch,
    recreation,
    socialTime,
    staircase,
    storage,
    studio,
    terrace,
    toilet,
    comingHome,
    daytime,
    goToSleep,
    homeAway,
    leavingHome,
    location,
    nighttime,
    otherApps,
    personal,
    sunrise,
    sunset,
    timers,
    wakeUp,
    about,
    appleWatch,
    devices,
    feedback,
    homekitSiri,
    httpsConnected,
    login,
    messaging,
    softwareUpdate,
    widgets,
    widgetsWatch,
    automation,
    explore,
    home,
    homeNoCon,
    routines,
    settings,
    settingsLts,
    attention,
    blink,
    colorloop,
    colorScenes,
    confirmed,
    destroy,
    doNothing,
    dynamicScenes,
    edit,
    error,
    export,
    lastState,
    lightList,
    minus,
    motionSensitivity,
    noMotion,
    photoScene,
    plus,
    scenes,
    switchOff,
    switchOn,
    firstFloor,
    groundFloor,
    secondFloor,
  ];
}
