/// Flutter icons HueIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
library;

import 'package:flutter/widgets.dart';

/// These icons represent the different types of lights that Philips Hue has to
/// offer.
class HueIcon {
  HueIcon._();

  static const _kFontFam = 'HueIcon';
  static const String _kFontPkg = 'flutter_hue';

  static const IconData bollard =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData candleBulb =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData ceilingHorizontal =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData ceilingRound =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData ceilingSquare =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData ceilingTube =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData christmasTree =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData classicBulb =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData doubleSpot =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData edisonBulb =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData ellipseBulb =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData flexibleLamp =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData floodBulb =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData floorLantern =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData floorShade =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData hueBloom =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData groundSpot =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData hueCentris =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData hueGo =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData hueIris =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData hueLightstripPc =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData hueLightstripTv =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData hueLightstrip =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData huePlay =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData hueSigne =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData hueTube =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData largeGlobeBulb =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData lusterBulb =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData pendantLong =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData pendantRound =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData pendantSpot =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData recessedCeiling =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData recessedFloor =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData singleSpot =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData smallGlobeBulb =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData spotBulb =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData stringLight =
      IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData sultanBulb =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData tableShade =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData tableWash =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData triangleBulb =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData vintageBulb =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData vintageCandleBulb =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData wallLantern =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData wallShade =
      IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData wallSpot =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData wallWasher =
      IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const List<IconData> allIcons = [
    bollard,
    candleBulb,
    ceilingHorizontal,
    ceilingRound,
    ceilingSquare,
    ceilingTube,
    christmasTree,
    classicBulb,
    doubleSpot,
    edisonBulb,
    ellipseBulb,
    flexibleLamp,
    floodBulb,
    floorLantern,
    floorShade,
    hueBloom,
    groundSpot,
    hueCentris,
    hueGo,
    hueIris,
    hueLightstripPc,
    hueLightstripTv,
    hueLightstrip,
    huePlay,
    hueSigne,
    hueTube,
    largeGlobeBulb,
    lusterBulb,
    pendantLong,
    pendantRound,
    pendantSpot,
    recessedCeiling,
    recessedFloor,
    singleSpot,
    smallGlobeBulb,
    spotBulb,
    stringLight,
    sultanBulb,
    tableShade,
    tableWash,
    triangleBulb,
    vintageBulb,
    vintageCandleBulb,
    wallLantern,
    wallShade,
    wallSpot,
    wallWasher,
  ];
}
