name: flutter_hue
description: An SDK designed for the Flutter framework that enables developers
  to easily integrate Philips Hue smart devices into their applications.
version: 1.2.5
repository: https://github.com/babincc/flutter_workshop/tree/master/packages/flutter_hue
issue_tracker: https://github.com/babincc/flutter_workshop/issues?q=is%3Aissue+is%3Aopen+label%3A%22package%3A+flutter_hue%22

topics:
  - philips-hue
  - smart-lights

funding:
  - https://www.buymeacoffee.com/babincc
  - https://paypal.me/cssbabin
  - https://venmo.com/u/babincc

environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:
  collection: ^1.17.0
  crypto: ^3.0.2
  dtls2: ^0.16.0
  flutter:
    sdk: flutter
  flutter_openssl_crypto: ^0.3.0
  http: ^1.0.0
  multicast_dns: ^0.3.2+3
  path_provider: ^2.0.13
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  fonts:
    - family: HueIcon
      fonts:
        - asset: packages/flutter_hue/assets/fonts/HueIcon.ttf
    - family: HueIconV1
      fonts:
        - asset: packages/flutter_hue/assets/fonts/HueIconV1.ttf
