name: flutter_hue
description: An SDK designed for the Flutter framework that enables developers
  to easily integrate Philips Hue smart devices into their applications.
version: 2.0.0-beta.5
repository: https://github.com/babincc/flutter_workshop/tree/master/packages/flutter_hue
issue_tracker: https://github.com/babincc/flutter_workshop/issues?q=is%3Aissue+is%3Aopen+label%3A%22package%3A+flutter_hue%22

topics:
  - philips-hue
  - smart-lights

funding:
  - https://www.buymeacoffee.com/babincc
  - https://paypal.me/cssbabin
  - https://venmo.com/u/babincc

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.0
  crypto: ^3.0.2
  dtls2: ^0.17.0
  flutter:
    sdk: flutter
  http: ^1.0.0
  multicast_dns: ^0.3.2+3
  path_provider: ^2.0.13
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.hexcat.flutter_hue
        pluginClass: FlutterHuePlugin
      ios:
        pluginClass: FlutterHuePlugin
      linux:
        pluginClass: FlutterHuePlugin
      macos:
        pluginClass: FlutterHuePlugin
      windows:
        pluginClass: FlutterHuePluginCApi

  fonts:
    - family: HueIcon
      fonts:
        - asset: packages/flutter_hue/assets/fonts/HueIcon.ttf
    - family: HueIconV1
      fonts:
        - asset: packages/flutter_hue/assets/fonts/HueIconV1.ttf
