name: flutter_hue
description: An SDK designed for the Flutter framework that enables developers to easily integrate Philips Hue smart devices into their applications.
version: 1.2.0
repository: https://github.com/babincc/flutter_workshop/tree/master/packages/flutter_hue
issue_tracker: https://github.com/babincc/flutter_workshop/labels/plugin%3A%20flutter_hue

environment:
  sdk: '>=2.19.2 <3.0.0'
  # flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.0
  crypto: ^3.0.2
  flutter:
    sdk: flutter
  http: ^0.13.5
  multicast_dns: ^0.3.2+3
  path_provider: ^2.0.13
  # universal_html: ^2.2.1
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: HueIcon
      fonts:
      - asset: packages/flutter_hue/assets/fonts/HueIcon.ttf
    - family: HueIconV1
      fonts:
      - asset: packages/flutter_hue/assets/fonts/HueIconV1.ttf
