name: my_skeleton
description: This is skeleton or starter code for a new Flutter project.
publish_to: "none"
version: 1.2.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cloud_firestore: ^4.0.4
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.1.2
  flutter:
    sdk: flutter
  flutter_typeahead: ^5.2.0
  google_fonts: ^6.1.0
  go_router: ^14.1.2
  intl: ^0.19.0
  path_provider: ^2.0.8
  provider: ^6.0.2
  stack_trace: ^1.11.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  # flutter pub global activate rename
  # rename setAppName --targets ios,android --value "My Skeleton"
  rename: ^3.0.2

flutter_launcher_icons: # dart run flutter_launcher_icons
  android: true
  ios: true
  image_path: "dev/images/logo.jpg"
  image_path_android: "dev/images/logo.jpg"
  web:
    generate: true
    image_path: "dev/images/logo.jpg"
  windows:
    generate: true
    image_path: "dev/images/logo.jpg"
  macos:
    generate: true
    image_path: "dev/images/logo_mac.png"

flutter_native_splash: # dart run flutter_native_splash:create
  color: "#f6f6f6"
  image: "dev/images/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
