name: n_dimensional_array
description: Allows for the creation and easy manipulation of n-dimensional
  arrays in Flutter.
version: 1.0.3
repository: https://github.com/babincc/flutter_workshop/tree/master/packages/n_dimensional_array
issue_tracker: https://github.com/babincc/flutter_workshop/issues?q=is%3Aissue+is%3Aopen+label%3A%22package%3A+n_dimensional_array%22

topics:
  - multidimensional-array
  - nested-list

funding:
  - https://www.buymeacoffee.com/babincc
  - https://paypal.me/cssbabin
  - https://venmo.com/u/babincc

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  collection: ^1.17.1

dev_dependencies:
  test: ^1.24.4
  flutter_lints: ^2.0.0
