name: example
description: Demonstrates how to use the dynamic_background package.
publish_to: "none"
version: 0.3.0

environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  dynamic_background:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  lints: ^5.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
