name: radio_group_v2
description: A widget that groups radio buttons so they can work together to
  give the user a pleasant experience when making selections within the app.
version: 3.1.0
repository: https://github.com/babincc/flutter_workshop/tree/master/packages/radio_group_v2
issue_tracker: https://github.com/babincc/flutter_workshop/issues?q=is%3Aissue+is%3Aopen+label%3A%22package%3A+radio_group_v2%22

topics:
  - radio-group
  - radio-buttons

funding:
  - https://www.buymeacoffee.com/babincc
  - https://paypal.me/cssbabin
  - https://venmo.com/u/babincc

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
