name: dynamic_background
description: Allows developers to create animated backgrounds for their Flutter
  apps.
version: 0.3.0
repository: https://github.com/babincc/flutter_workshop/tree/master/packages/dynamic_background
issue_tracker: https://github.com/babincc/flutter_workshop/issues?q=is%3Aissue+is%3Aopen+label%3A%22package%3A+dynamic_background%22

topics:
  - animated-background
  - live-background

funding:
  - https://www.buymeacoffee.com/babincc
  - https://paypal.me/cssbabin
  - https://venmo.com/u/babincc

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  lints: ^5.1.1
