name: example
description: Demonstrates how to use the radio_group_v2 package.
publish_to: "none"
version: 3.1.1

environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  radio_group_v2:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
