name: example
description: Demonstrates how to use the radio_group_v2 package.
publish_to: "none"
version: 3.3.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  radio_group_v2:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.1.1

flutter:
  uses-material-design: true
